# Generated by Django 4.2.2 on 2024-08-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='документ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата обновления')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True, verbose_name='подтверждение документа')),
                ('is_rejected', models.BooleanField(blank=True, default=False, null=True, verbose_name='отклонение документа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
    ]
